# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=11, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='收件地址')),
                ('postcode', models.CharField(max_length=6, verbose_name='邮编')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='收件人手机号')),
                ('tag', models.CharField(max_length=11, verbose_name='标签')),
                ('isDefault', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否为活跃地址')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='The_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('isActive', models.BooleanField(default=False, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='WeiBoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuid', models.CharField(db_index=True, max_length=50)),
                ('access_token', models.CharField(max_length=100)),
                ('uid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.The_user')),
            ],
            options={
                'db_table': 'weibo_user',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.The_user'),
        ),
    ]
